/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.objective.fizzbuzz;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    private final App app = new App();

    @Test
    void should_return_Fizz() {

        assertEquals("Fizz",app.fizzBuzz(3));
    }

    @Test
    void should_return_Buzz() {
        assertEquals("Buzz",app.fizzBuzz(5));
    }

    @Test
    void should_return_FizzBuzz() {
        assertEquals("Fizz Buzz", app.fizzBuzz(15));
    }

}
