/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.objective.fizzbuzz;

import java.util.stream.IntStream;

public class App {

    public static void main(String[] args) {
        var app = new App();

        for (int i = 1; i <= 100; i ++) {
            System.out.println(app.fizzBuzz(i));
        }

        System.out.println("===============");
        System.out.println("Fizz Buzz with IntStream");
        IntStream.rangeClosed(1,100)
                .mapToObj(i -> i % 3 == 0 ? (i % 5 == 0 ? "Fizz Buzz" : "Fizz") : (i % 5 == 0 ? "Buzz" : i))
                .forEach(System.out::println);

        System.out.println("===============");
        System.out.println("Fizz Buzz with a Class");
        for (int num = 1; num <= 100; num ++) {
            System.out.println(new FizzBuzzSimple(num).getFizzBuzzNumber());
        }

        System.out.println("===============");
        System.out.println("FizzBuzz with Chain of Responsability");
        FizzBuzz fizzBuzz = new FizzBuzz(new Fizz(new Buzz(new NotFizzBuzz())));

        for (int num = 1; num <= 100; num ++) {
            System.out.println(fizzBuzz.checkFizzBuzz(num));
        }
    }

    public String fizzBuzz(int i) {
        if (i % 3 == 0 && i % 5 == 0) return "Fizz Buzz";
        if (i % 3 == 0) return "Fizz";
        if (i % 5 == 0) return "Buzz";
        return String.valueOf(i);
    }

}
